events {
    worker_connections 1024;
}
http {

server {
    listen 80;
    server_name young-frida.com;
    return 301 https://$host$request_uri; # Force HTTP to HTTPS
}

server {
    listen 443 ssl;
    server_name test-app01.com;

    ssl_certificate     /etc/nginx/ssl/test-app01.crt;
    ssl_certificate_key /etc/nginx/ssl/test-app01.key;

    location / {
        proxy_pass http://young-frida:3000;
        proxy_set_header Host $host;
    }
}
}
